name: Publish UPM Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upm-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create GPU Release for OpenUPM
      id: create_gpu_release
      uses: quabug/create-upm-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target: main
        upm_tag_prefix: gpu/v
        upm_package_path: Packages/com.quabug.parallel-counting-sort.gpu
        create_unitypackage: true
        unitypackage_name: parallel-counting-sort.gpu
    - name: Create CPU Release for OpenUPM
      id: create_cpu_release
      uses: quabug/create-upm-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target: main
        upm_tag_prefix: cpu/v
        upm_package_path: Packages/com.quabug.parallel-counting-sort.cpu
        create_unitypackage: true
        unitypackage_name: parallel-counting-sort.cpu
